INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'CENTENO ZAPATA', 'GONZALO JAVIER');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'RAMIREZ', 'OSCAR');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'RAMIREZ', 'OSCAR');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'RIVEROS', 'MARCOS');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'MARLENE');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'CACERES', 'PATRICIA');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'PACHAURI', 'JAIME');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'AURELIO', 'EDMUNDO');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'RIVEROS', 'SARA');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'CARLA');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'MAMANI', 'MONICA');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'CACERES', 'VICTOR');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'PEREZ', 'JORGE');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VILCA', 'DANILO');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'ROSAS', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'PAREDES', 'FERNANDO');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'BLANCO', ' LURDES');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALDEZ', 'JUAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'FUJIMORI', 'KEIKO');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'GARCIA', 'ALAN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'VALVERDE', 'KATERHIN');
INSERT INTO persona (id_persona, apellidos, nombres) VALUES(DEFAULT,'GARCIA', 'GONZALO');

INSERT INTO producto (marca, nombre) VALUES('TOSHIBA', 'LAPTOP');
INSERT INTO producto (marca, nombre) VALUES('SAMSUNG', 'TV 55 PULGADAS');
INSERT INTO producto (marca, nombre) VALUES('HUAWEI', 'HUAWEI P9 LITE');